name: Notification on push

on:
  push:
    branches:
    - 'test'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        DISCORD_USERNAME: OSS 117
        DISCORD_AVATAR: https://resize.programme-television.ladmedia.fr/r/670,670/img/var/premiere/storage/images/tele-7-jours/news-tv/oss-117-le-caire-nid-d-espions-c8-le-show-de-jean-dujardin-4484285/90175763-1-fre-FR/OSS-117-Le-Caire-nid-d-espions-C8-Le-show-de-Jean-Dujardin.jpg
        DISCORD_MULTILINE: 0
      uses: EBfVince/action-discord@master
      with:
        args: 'Release notes:\n- 🚀 New features\n- ✨ Cool stuff\n- 🎨 Salut <@520303597234159618> <:vince:752545539974758400>'
